### PR TITLE
Update Serdes.luau - Client infinite yield warning

### PR DESCRIPTION
**Pull request by xArshy**
Added a warning for yielding identifiers on the client. (10s)

### CODE REVIEW

**Review by imezx — CHANGES_REQUESTED** [review]
local loaded = false
task.delay(10, function()
	if loaded then return end
	warn(`{Identifier} is taking too long to retrieve.`)
end)

while (not loaded) and (not Event:GetAttribute(Identifier)) do
	task.wait(0.5)
end
loaded = true


change to this.

**Comment by xArshy** [comment]
> local loaded = false task.delay(10, function() if loaded then return end warn(`{Identifier} is taking too long to retrieve.`) end)
> 
> while (not loaded) and (not Event:GetAttribute(Identifier)) do task.wait(0.5) end loaded = true
> 
> change to this.

loaded is never set to true before the while loop though.

**Comment by imezx** [comment]
> loaded is never set to true before the while loop though.

what? loaded supposed to be last/after while loop, did u see there (not loaded) at while state? and on task.delay there statement if  it been loaded then it return.

**Comment by imezx** [comment]
i will think about this later.

**Comment by xArshy** [comment]
Uhhh what?
> not loaded and not attribute
this means if not loaded it'll continue yielding even if attribute is not nil

**Pull request closed without merging**
