### PR TITLE
Key is a string

### PR DESCRIPTION
**Pull request by xArshy**
Rather than unnecessarily calling `tostring()` on the key, just return a string.
Deleted redundant ClientProcess.luau to avoid conflicts.

### CODE REVIEW

**Comment by imezx** [comment]
that was intentional.

**Comment by imezx** [comment]
for key.

**Comment by imezx** [comment]
u can create new pr for that ClientProcess.luau

**Comment by xArshy** [comment]
> that was intentional.

Could you explain how?
string.sub(number, x, y) already returns a string.
So why bother converting a string into a number then into a string... ?

**Comment by imezx** [comment]
key is intentional to return number.

**Comment by xArshy** [comment]
Yes, but why? 
You're not explaining why...

**Pull request closed without merging**
